"use client";

import { useState, type ReactNode } from "react";
import Link from "next/link";
import {
  LuArrowDown,
  LuBadgeCheck,
  LuBellRing,
  LuBraces,
  LuCalendarClock,
  LuCheck,
  LuCircleHelp,
  LuCopy,
  LuDatabase,
  LuEye,
  LuFileText,
  LuGitBranch,
  LuLightbulb,
  
  LuLockOpen,
  LuLock,
  LuMail,
  LuRefreshCw,
  LuRoute,
  LuSend,
  LuSettings2,
  LuShield,
  LuTable2,
  LuUserRound,
  LuUsers,
  LuWorkflow,
} from "react-icons/lu";

const customEmailSource = `<h1>Quickbase Automation Lab</h1>

<h2>Custom Email Observation</h2>

<p>
  A Custom Email was generated because a qualifying Task record changed.
</p>

<hr>

<h2>Record Change</h2>

<p>
  The section below is generated by Quickbase from the record-change event.
  It identifies the changed record and shows the fields that were edited,
  including their previous and new values.
</p>

<qb-changes></qb-changes>

<hr>

<h2>Recipient Experiment</h2>

<p>
  <strong>Recipient source:</strong> User in Assigned To
</p>

<p>
  This recipient is not permanently stored in the email definition as one
  specific person. Quickbase determines the recipient from the User value
  stored in the Task record when the Custom Email is evaluated.
</p>

<hr>

<h2>Automation Context</h2>

<table style="width:100%; border-collapse:collapse;">
  <tbody>
    <tr>
      <td style="padding:6px;"><strong>Trigger</strong></td>
      <td style="padding:6px;">Task record modified</td>
    </tr>
    <tr>
      <td style="padding:6px;"><strong>Recipient source</strong></td>
      <td style="padding:6px;">User in Assigned To</td>
    </tr>
    <tr>
      <td style="padding:6px;"><strong>Permission mode</strong></td>
      <td style="padding:6px;">Check recipient permissions</td>
    </tr>
    <tr>
      <td style="padding:6px;"><strong>Bulk behavior</strong></td>
      <td style="padding:6px;">Send a single email with all changes</td>
    </tr>
  </tbody>
</table>

<hr>

<h2>Open the Task</h2>

<p>
  <qb-marker type="record-link"></qb-marker>
</p>

<hr>

<p>
  <strong>Quickbase Automation Developer Lab</strong><br>
  Lesson 4 — Custom Email
</p>`;

function SectionHeading({
  eyebrow,
  title,
  icon,
  children,
}: {
  eyebrow?: string;
  title: string;
  icon?: ReactNode;
  children?: ReactNode;
}) {
  return (
    <div className="mb-6">
      {eyebrow && (
        <p className="mb-2 font-bold uppercase tracking-[0.12em] text-[#276749]">
          {eyebrow}
        </p>
      )}
      <div className="flex items-start gap-4">
        {icon && (
          <span className="mt-1 flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#e6f4ea] text-2xl text-[#276749]">
            {icon}
          </span>
        )}
        <div>
          <h2 className="text-3xl font-bold text-[#205c38] sm:text-4xl">
            {title}
          </h2>
          {children && (
            <div className="mt-4 max-w-4xl text-lg leading-8">{children}</div>
          )}
        </div>
      </div>
    </div>
  );
}

function ConceptCard({
  title,
  icon,
  children,
}: {
  title: string;
  icon?: ReactNode;
  children: ReactNode;
}) {
  return (
    <div className="group rounded-xl border border-gray-300 bg-white p-6 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-[#9fc9ad] hover:shadow-md">
      <div className="flex items-start gap-4">
        {icon && (
          <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[#f0fff4] text-xl text-[#276749] transition-transform duration-200 group-hover:scale-105">
            {icon}
          </span>
        )}
        <h3 className="pt-1 text-xl font-bold text-[#205c38]">{title}</h3>
      </div>
      <div className="mt-4 leading-8">{children}</div>
    </div>
  );
}

function Remember({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div className="my-8 rounded-xl border-2 border-[#d4a72c] bg-[#fffaf0] p-6">
      <div className="flex items-start gap-4">
        <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-white text-xl text-[#7a5200] shadow-sm">
          <LuLightbulb aria-hidden="true" />
        </span>
        <div>
          <p className="font-bold uppercase tracking-[0.12em] text-[#7a5200]">
            Remember This
          </p>
          <h3 className="mt-2 text-xl font-bold">{title}</h3>
        </div>
      </div>
      <div className="mt-4 leading-8">{children}</div>
    </div>
  );
}

function Discovery({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <div className="my-8 rounded-2xl border-2 border-[#276749] bg-[#f0fff4] p-6 sm:p-7">
      <div className="flex items-start gap-4">
        <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-white text-2xl text-[#276749] shadow-sm">
          <LuEye aria-hidden="true" />
        </span>
        <div>
          <p className="font-bold uppercase tracking-[0.12em] text-[#276749]">
            Observed in Our Lab
          </p>
          <h3 className="mt-2 text-2xl font-bold text-[#205c38]">{title}</h3>
        </div>
      </div>
      <div className="mt-5 leading-8">{children}</div>
    </div>
  );
}

function ReviewCard({ children }: { children: ReactNode }) {
  return (
    <div className="my-6 rounded-xl border border-[#9fc9ad] bg-[#f0fff4] p-5">
      <p className="font-bold uppercase tracking-[0.12em] text-[#276749]">
        Review 3A–3B
      </p>
      <div className="mt-3 leading-7">{children}</div>
    </div>
  );
}

function QuestionCard({
  question,
  children,
}: {
  question: string;
  children: ReactNode;
}) {
  return (
    <div className="rounded-xl border-2 border-[#9fc9ad] bg-[#f0fff4] p-6">
      <div className="flex items-start gap-4">
        <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-white text-2xl text-[#276749] shadow-sm">
          <LuCircleHelp aria-hidden="true" />
        </span>
        <div>
          <p className="text-sm font-bold uppercase tracking-[0.14em] text-[#276749]">
            Central Question
          </p>
          <h2 className="mt-2 text-2xl font-bold text-[#205c38] sm:text-3xl">
            {question}
          </h2>
        </div>
      </div>
      <div className="mt-4 max-w-4xl text-lg leading-8">{children}</div>
    </div>
  );
}

function FlowArrow() {
  return (
    <div className="flex h-10 items-center justify-center">
      <LuArrowDown aria-hidden="true" className="text-xl text-[#276749]/60" />
    </div>
  );
}

function FlowStep({
  icon,
  title,
  description,
  final = false,
}: {
  icon: ReactNode;
  title: string;
  description?: string;
  final?: boolean;
}) {
  return (
    <div
      className={`w-full rounded-xl border p-4 shadow-sm ${
        final
          ? "border-[#276749] bg-[#276749] text-white"
          : "border-[#b7d8c2] bg-white"
      }`}
    >
      <div className="flex items-start gap-4">
        <span
          className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg text-xl ${
            final ? "bg-white/15 text-white" : "bg-[#f0fff4] text-[#276749]"
          }`}
        >
          {icon}
        </span>
        <div>
          <h4
            className={`font-extrabold ${final ? "text-white" : "text-[#205c38]"}`}
          >
            {title}
          </h4>
          {description && (
            <p
              className={`mt-1 text-sm leading-6 ${final ? "text-white/85" : "text-gray-600"}`}
            >
              {description}
            </p>
          )}
        </div>
      </div>
    </div>
  );
}

function MentalModel({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <div className="my-8 overflow-hidden rounded-2xl border-2 border-[#9fc9ad] bg-[#f0fff4]">
      <div className="border-b border-[#9fc9ad] bg-[#e6f4ea] px-6 py-5">
        <div className="flex items-center gap-3">
          <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-xl text-[#276749] shadow-sm">
            <LuRoute aria-hidden="true" />
          </span>
          <div>
            <p className="font-bold uppercase tracking-[0.12em] text-[#276749]">
              Mental Model
            </p>
            <h3 className="mt-1 text-xl font-bold text-[#205c38]">{title}</h3>
          </div>
        </div>
      </div>
      <div className="p-6 sm:p-7">{children}</div>
    </div>
  );
}

function CodeBlock({ code }: { code: string }) {
  const [copied, setCopied] = useState(false);

  async function copy() {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div className="overflow-hidden rounded-xl border border-gray-300 bg-[#111827] shadow-sm">
      <div className="flex items-center justify-between gap-4 border-b border-white/10 px-5 py-3">
        <p className="text-sm font-bold uppercase tracking-[0.12em] text-gray-300">
          Lesson 4 Laboratory Source
        </p>
        <button
          type="button"
          onClick={copy}
          className="inline-flex items-center gap-2 rounded-lg border border-white/15 bg-white/10 px-3 py-2 text-sm font-bold text-white hover:bg-white/15"
        >
          {copied ? <LuCheck /> : <LuCopy />}
          {copied ? "Copied" : "Copy Source"}
        </button>
      </div>
      <pre className="overflow-x-auto p-5 text-sm leading-7 text-gray-100">
        <code>{code}</code>
      </pre>
    </div>
  );
}

export default function LessonFourPage() {
  return (
    <main className="min-h-screen bg-white text-black">
      <header className="relative overflow-hidden border-b border-[#17452a] bg-[#276749] text-white">
        <div
          aria-hidden="true"
          className="absolute right-0 top-0 h-64 w-64 rounded-full bg-white/10 blur-3xl"
        />
        <div className="relative mx-auto max-w-6xl px-6 py-12 lg:px-8 lg:py-14">
          <p className="mb-3 font-bold uppercase tracking-[0.18em] text-white/80">
            Quickbase Automation Developer Lab
          </p>
          <p className="mb-2 text-lg font-semibold text-white/90">Lesson 4</p>
          <h1 className="max-w-5xl text-4xl font-extrabold leading-tight sm:text-5xl">
            Custom Email: Why Does It Exist?
          </h1>
          <p className="mt-6 max-w-4xl text-xl leading-9 text-white">
            Notifications already react to events, evaluate conditions, select
            recipients, and send messages. Lesson 4 investigates why Quickbase
            also provides Custom Email—and when a builder should choose one
            email mechanism over another.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <Link
              href="/lessons/3b"
              className="inline-flex rounded-lg border-2 border-white px-5 py-3 font-bold text-white hover:bg-white hover:text-[#276749]"
            >
              ← Previous Lesson
            </Link>
            <Link
              href="/lessons/5"
              className="inline-flex rounded-lg border-2 border-white px-5 py-3 font-bold text-white transition hover:-translate-y-0.5 hover:bg-white hover:text-[#276749]"
            >
              Next Lesson →
            </Link>{" "}            
            <Link
              href="/lessons"
              className="inline-flex rounded-lg bg-white px-5 py-3 font-bold text-[#276749] hover:bg-[#f0fff4]"
            >
              Table of Contents
            </Link>
          </div>
        </div>
      </header>

      <article className="mx-auto max-w-6xl px-6 pb-20 pt-10 lg:px-8">
        <section className="mb-14">
          <QuestionCard question="If Notifications can already do all of this, what problem is Custom Email intended to solve?">
            <p>
              We do not assume that newer automatically means better. We compare
              architecture, capabilities, recipients, permissions, content, and
              delivery behavior.
            </p>
          </QuestionCard>
        </section>

        <section className="mb-14">
          <SectionHeading
            eyebrow="Part 1"
            title="Start With the Four Email Choices"
            icon={<LuMail />}
          >
            <p>
              By Lesson 4, Notification has already proven capable. Custom Email
              now has to justify its existence as something more than another
              button.
            </p>
          </SectionHeading>

          <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
            <ConceptCard title="Custom Email" icon={<LuMail />}>
              <p>Modern, richer email construction and delivery.</p>
            </ConceptCard>
            <ConceptCard title="Notification" icon={<LuBellRing />}>
              <p>Legacy event-driven automatic email.</p>
            </ConceptCard>
            <ConceptCard title="Subscription" icon={<LuSend />}>
              <p>Scheduled report delivery.</p>
            </ConceptCard>
            <ConceptCard title="Reminder" icon={<LuCalendarClock />}>
              <p>Date-relative automatic email.</p>
            </ConceptCard>
          </div>

          <MentalModel title="Laboratory method">
            <div className="mx-auto flex max-w-xl flex-col items-center">
              <FlowStep icon={<LuEye />} title="Observe the UI" />
              <FlowArrow />
              <FlowStep icon={<LuTable2 />} title="Compare" />
              <FlowArrow />
              <FlowStep icon={<LuLightbulb />} title="Form a Model" />
              <FlowArrow />
              <FlowStep icon={<LuSettings2 />} title="Change One Variable" />
              <FlowArrow />
              <FlowStep icon={<LuEye />} title="Test and Observe" />
              <FlowArrow />
              <FlowStep icon={<LuGitBranch />} title="Refine the Model" final />
            </div>
          </MentalModel>
        </section>

        <section className="mb-14">
          <SectionHeading
            eyebrow="Part 2"
            title="Inspect the Custom Email Architecture"
            icon={<LuSettings2 />}
          >
            <p>
              The editor exposes Basics, Send options, Settings, and Compose
              email. This immediately suggests a broader system than a simple
              legacy message editor.
            </p>
          </SectionHeading>

          <div className="grid gap-5 md:grid-cols-2">
            <ConceptCard title="Basics" icon={<LuFileText />}>
              <p>Name and description identify the automation.</p>
            </ConceptCard>
            <ConceptCard title="Send options" icon={<LuRoute />}>
              <p>
                Start from a record event or a recurring schedule. Event mode
                also exposes record events, fields, conditions, and all/any
                logic.
              </p>
            </ConceptCard>
            <ConceptCard title="Settings" icon={<LuShield />}>
              <p>
                Bulk-change behavior and recipient permissions/data access are
                explicit.
              </p>
            </ConceptCard>
            <ConceptCard title="Compose email" icon={<LuMail />}>
              <p>
                From, To, Subject, rich content, Add Elements, and Source
                editing.
              </p>
            </ConceptCard>
          </div>

          <ReviewCard>
            Event criteria, watched fields, after-change conditions, all/any,
            and Boolean evaluation were already investigated in Lessons 3A–3B.
            Lesson 4 does not reteach them.
          </ReviewCard>
        </section>

        <section className="mb-14">
          <SectionHeading
            eyebrow="Decision Framework"
            title="Why Choose Custom Email?"
            icon={<LuCircleHelp />}
          >
            <p>
              The important distinction is not merely that Custom Email looks
              newer. It consolidates use cases formerly split across legacy
              email types and extends them with richer composition, delivery,
              permission, and content capabilities.
            </p>
          </SectionHeading>

          <div className="grid gap-5 lg:grid-cols-3">
            <ConceptCard
              title="Prefer Custom Email when..."
              icon={<LuBadgeCheck />}
            >
              <ul className="space-y-3">
                <li>You are building a new automatic email.</li>
                <li>You need record-event or recurring scheduled delivery.</li>
                <li>
                  You want richer composition, CC/BCC, forms, reports, charts,
                  or attachments.
                </li>
                <li>You need dynamic recipients from User fields.</li>
                <li>You need explicit recipient-permission behavior.</li>
                <li>You need deliberate bulk-change delivery behavior.</li>
                <li>
                  You want native Record Change elements or richer Quickbase
                  elements.
                </li>
              </ul>
            </ConceptCard>

            <ConceptCard
              title="Keep a legacy Notification when..."
              icon={<LuBellRing />}
            >
              <ul className="space-y-3">
                <li>An existing Notification already works correctly.</li>
                <li>The requirement is simple and event-driven.</li>
                <li>Rebuilding produces no meaningful benefit.</li>
                <li>Migration/testing cost exceeds the value of change.</li>
              </ul>
            </ConceptCard>

            <ConceptCard
              title="Keep Reminder / Subscription when..."
              icon={<LuCalendarClock />}
            >
              <ul className="space-y-3">
                <li>
                  An existing legacy automation already solves the need cleanly.
                </li>
                <li>The app depends on established behavior.</li>
                <li>
                  You are maintaining a stable application rather than
                  redesigning it.
                </li>
              </ul>
            </ConceptCard>
          </div>

          <Remember title="Modern default does not mean mandatory migration">
            <p>
              For a new automatic-email requirement, Custom Email is usually the
              first mechanism worth evaluating. Existing Notifications,
              Reminders, and Subscriptions do not become defective simply
              because the newer system exists.
            </p>
            <p className="mt-4">
              Ask which mechanism solves the requirement with the least
              unnecessary complexity while preserving the behavior the
              application actually needs.
            </p>
          </Remember>

          <div className="rounded-2xl border border-[#9fc9ad] bg-[#f0fff4] p-6 sm:p-8">
            <p className="font-bold uppercase tracking-[0.12em] text-[#276749]">
              Rule of Thumb
            </p>
            <div className="mt-5 grid gap-4 md:grid-cols-3">
              <div className="rounded-xl bg-white p-5">
                <p className="font-bold text-[#205c38]">New build</p>
                <p className="mt-2">
                  Evaluate <strong>Custom Email</strong> first.
                </p>
              </div>
              <div className="rounded-xl bg-white p-5">
                <p className="font-bold text-[#205c38]">
                  Existing simple automation
                </p>
                <p className="mt-2">
                  Keep it unless Custom Email solves a real limitation.
                </p>
              </div>
              <div className="rounded-xl bg-white p-5">
                <p className="font-bold text-[#205c38]">
                  Richer communication requirement
                </p>
                <p className="mt-2">
                  Custom Email becomes the stronger candidate.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="mb-14">
          <SectionHeading
            eyebrow="Parts 3–5"
            title="Dynamic Recipients Extend the Model"
            icon={<LuUsers />}
          >
            <p>
              The Tasks table exposed static users, roles/audiences, and
              User-field recipients such as User in Assigned To.
            </p>
          </SectionHeading>

          <div className="grid gap-5 md:grid-cols-3">
            <ConceptCard title="Static Recipient" icon={<LuUserRound />}>
              <p>A specific known person.</p>
            </ConceptCard>
            <ConceptCard title="Role / Audience" icon={<LuUsers />}>
              <p>Users belonging to a selected Quickbase role or audience.</p>
            </ConceptCard>
            <ConceptCard title="Record-Derived" icon={<LuDatabase />}>
              <p>A user stored in a User field on the qualifying record.</p>
            </ConceptCard>
          </div>

          <MentalModel title="Assigned To becomes a recipient source">
            <div className="mx-auto flex max-w-xl flex-col items-center">
              <FlowStep
                icon={<LuDatabase />}
                title="Assigned To"
                description="Field Type = User"
              />
              <FlowArrow />
              <FlowStep
                icon={<LuUserRound />}
                title="User in Assigned To"
                description="Custom Email recipient option"
              />
              <FlowArrow />
              <FlowStep icon={<LuMail />} title="Dynamic Recipient" final />
            </div>
          </MentalModel>

          <Discovery title="Experiment 4.2 — the resulting assignee received the email">
            <div className="mx-auto flex max-w-xl flex-col items-center">
              <FlowStep
                icon={<LuUserRound />}
                title="Old State"
                description="Assigned To = User A"
              />
              <FlowArrow />
              <FlowStep icon={<LuRefreshCw />} title="Modify and Save" />
              <FlowArrow />
              <FlowStep
                icon={<LuUserRound />}
                title="New State"
                description="Assigned To = User B"
              />
              <FlowArrow />
              <FlowStep
                icon={<LuMail />}
                title="Resolve Recipient"
                description="User in Assigned To = User B"
              />
              <FlowArrow />
              <FlowStep icon={<LuSend />} title="Email → User B" final />
            </div>
            <p className="mt-5">
              User B received the email. User A did not. In this reassignment
              experiment, the dynamic recipient was resolved from the
              resulting/current Assigned To value after Save.
            </p>
          </Discovery>

          <Remember title="Current assignee and previous assignee are different requirements">
            <p>
              “Notify the person assigned now” does not automatically mean
              “notify the person who was assigned before the modification.”
            </p>
          </Remember>
        </section>

        <section className="mb-14">
          <SectionHeading
            eyebrow="Parts 6–8"
            title="Custom Email Uses Its Own Source Elements"
            icon={<LuBraces />}
          >
            <p>
              Typing legacy-style strings such as <code>[Task Name]</code> or{" "}
              <code>[Status]</code>
              into the modern Custom Email content did not automatically resolve
              them into record values during our experiment.
            </p>
          </SectionHeading>

          <div className="grid gap-5 md:grid-cols-2">
            <ConceptCard title="Quickbase field element" icon={<LuDatabase />}>
              <p className="font-mono text-sm">
                {'<qb-field field-id="12"></qb-field>'}
              </p>
            </ConceptCard>
            <ConceptCard
              title="Native Record Change element"
              icon={<LuRefreshCw />}
            >
              <p className="font-mono text-sm">{"<qb-changes></qb-changes>"}</p>
            </ConceptCard>
          </div>

          <div className="mt-8">
            <CodeBlock code={customEmailSource} />
          </div>

          <Discovery title="<qb-changes> produced a structured previous/current presentation">
            <div className="overflow-x-auto rounded-xl border border-gray-300 bg-white">
              <table className="w-full min-w-175 border-collapse text-left">
                <thead>
                  <tr className="border-b-2 border-[#276749] bg-[#f7f8fa]">
                    <th className="px-4 py-3">Field</th>
                    <th className="px-4 py-3">Previous value</th>
                    <th className="px-4 py-3">New value</th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    ["Date Modified", "previous timestamp", "new timestamp"],
                    ["Record ID#", "17", "17"],
                    ["Task Name", "previous value", "current value"],
                    ["Assigned To", "previous user", "new user"],
                  ].map((row) => (
                    <tr key={row[0]} className="border-b border-gray-200">
                      {row.map((cell, i) => (
                        <td key={i} className="px-4 py-3">
                          {cell}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p className="mt-5">
              Lesson 3A taught us to reason about previous → current. Lesson 4
              shows Custom Email presenting that transition through a native
              Record Change element.
            </p>
          </Discovery>
        </section>

        <section className="mb-14">
          <SectionHeading
            eyebrow="Parts 9–14"
            title="Security Becomes Part of Email Design"
            icon={<LuShield />}
          >
            <p>
              Custom Email explicitly separates recipient selection from the
              permission policy governing delivery and data access.
            </p>
          </SectionHeading>

          <div className="grid gap-5 md:grid-cols-2">
            <ConceptCard title="Check recipient permissions" icon={<LuLock />}>
              <p>
                Quickbase considers recipient access when determining
                delivery/data visibility.
              </p>
            </ConceptCard>
            <ConceptCard
              title="Ignore recipient permissions"
              icon={<LuLockOpen />}
            >
              <p>
                Delivery can proceed even when the recipient lacks the access
                that otherwise blocked it.
              </p>
            </ConceptCard>
          </div>

          <Remember title="Selectable recipient ≠ authorized recipient">
            <p>
              A person being selectable in a User field or recipient control
              does not necessarily mean Quickbase will deliver application data
              to that person under the current permission policy.
            </p>
          </Remember>

          <div className="overflow-x-auto rounded-xl border border-gray-300 bg-white">
            <table className="w-full min-w-225 border-collapse text-left">
              <thead>
                <tr className="border-b-2 border-[#276749] bg-[#f7f8fa]">
                  <th className="px-4 py-3">Test</th>
                  <th className="px-4 py-3">Recipient Configuration</th>
                  <th className="px-4 py-3">Tasks Access</th>
                  <th className="px-4 py-3">Observed Result</th>
                </tr>
              </thead>
              <tbody>
                {[
                  [
                    "1",
                    "All users with access to this table",
                    "Participant yes / Viewer no",
                    "Participant received; Viewer did not",
                  ],
                  ["2", "Viewer role", "No Tasks access", "No email"],
                  [
                    "3",
                    "User in Assigned To",
                    "Assigned user lacked Tasks access",
                    "No email",
                  ],
                  [
                    "4",
                    "Specific test user",
                    "User lacked Tasks access",
                    "No email",
                  ],
                ].map((row) => (
                  <tr key={row[0]} className="border-b border-gray-200">
                    {row.map((cell, i) => (
                      <td key={i} className="px-4 py-3">
                        {cell}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <Discovery title="Experiment 4.4 — changing only the permission mode changed the result">
            <div className="grid gap-5 md:grid-cols-2">
              <div className="rounded-xl border border-gray-300 bg-white p-5">
                <div className="flex items-center gap-3">
                  <LuLock className="text-xl text-[#276749]" />
                  <p className="font-bold text-[#205c38]">
                    Check recipient permissions
                  </p>
                </div>
                <p className="mt-4">
                  User without Tasks access → <strong>NO EMAIL</strong>
                </p>
              </div>
              <div className="rounded-xl border-2 border-[#276749] bg-[#276749] p-5 text-white">
                <div className="flex items-center gap-3">
                  <LuLockOpen className="text-xl" />
                  <p className="font-bold">Ignore recipient permissions</p>
                </div>
                <p className="mt-4">
                  Same user, same missing Tasks access →{" "}
                  <strong>EMAIL RECEIVED</strong>
                </p>
              </div>
            </div>
          </Discovery>

          <div className="rounded-2xl border-2 border-[#b45309] bg-[#fff7ed] p-6 sm:p-8">
            <div className="flex items-start gap-4">
              <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-white text-2xl text-[#b45309] shadow-sm">
                <LuShield />
              </span>
              <div>
                <p className="font-bold uppercase tracking-[0.12em] text-[#b45309]">
                  Security Principle
                </p>
                <h3 className="mt-2 text-2xl font-bold">
                  Ignore recipient permissions is a data-governance decision
                </h3>
              </div>
            </div>
            <div className="mt-6 grid gap-5 md:grid-cols-2">
              <div className="rounded-xl bg-white p-5">
                <p className="font-bold">Recipient selection</p>
                <p className="mt-2">Who should receive the message?</p>
              </div>
              <div className="rounded-xl bg-white p-5">
                <p className="font-bold">Permission policy</p>
                <p className="mt-2">
                  Whose Quickbase access governs what may be communicated?
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="mb-14">
          <SectionHeading
            eyebrow="Parts 15–16"
            title="Custom Email Is Broader Than a Prettier Notification"
            icon={<LuWorkflow />}
          >
            <p>
              By this point, the opening question has an evidence-based answer:
              Custom Email brings trigger logic, recipient logic, permission
              policy, bulk behavior, composition, and delivery into one modern
              email definition.
            </p>
          </SectionHeading>

          <div className="grid gap-5 md:grid-cols-3">
            <ConceptCard title="Trigger Logic" icon={<LuRoute />}>
              <p>Record event or schedule.</p>
            </ConceptCard>
            <ConceptCard title="Recipient Logic" icon={<LuUsers />}>
              <p>Static, role, audience, or record-derived.</p>
            </ConceptCard>
            <ConceptCard title="Content Design" icon={<LuBraces />}>
              <p>Rich content and native QB elements.</p>
            </ConceptCard>
            <ConceptCard title="Permissions" icon={<LuShield />}>
              <p>Explicit recipient-data access policy.</p>
            </ConceptCard>
            <ConceptCard title="Bulk Policy" icon={<LuTable2 />}>
              <p>How multi-record changes are handled.</p>
            </ConceptCard>
            <ConceptCard title="Delivery" icon={<LuSend />}>
              <p>One system coordinates the final communication.</p>
            </ConceptCard>
          </div>

          <div className="mt-8 overflow-x-auto rounded-xl border border-gray-300 bg-white">
            <table className="w-full min-w-245 border-collapse text-left">
              <thead>
                <tr className="border-b-2 border-[#276749] bg-[#f7f8fa]">
                  <th className="px-4 py-3">Capability</th>
                  <th className="px-4 py-3">Notification</th>
                  <th className="px-4 py-3">Custom Email</th>
                </tr>
              </thead>
              <tbody>
                {[
                  ["Record events", "✓", "✓"],
                  ["Watched fields", "✓", "✓"],
                  ["After-change conditions", "✓", "✓"],
                  ["Boolean evaluation", "✓", "✓"],
                  [
                    "Previous/current evidence",
                    "Manual techniques explored",
                    "Native Record Change element",
                  ],
                  [
                    "Dynamic User-field recipient",
                    "Available concepts differ",
                    "✓ tested",
                  ],
                  [
                    "Explicit recipient permission policy",
                    "Different / legacy model",
                    "✓",
                  ],
                  [
                    "Ignore recipient permissions",
                    "Different configuration model",
                    "✓ tested",
                  ],
                  ["Bulk delivery strategy", "Operation scope", "✓"],
                  [
                    "Recurring schedule",
                    "Separate legacy concepts",
                    "Exposed directly",
                  ],
                  ["Modern rich composer", "Legacy editor", "✓"],
                  [
                    "Source-mode QB elements",
                    "Different formatting model",
                    "✓",
                  ],
                  [
                    "Charts / rich embedded content",
                    "Legacy limitations",
                    "Stronger modern candidate",
                  ],
                  [
                    "File attachments",
                    "Legacy limitations",
                    "Richer attachment scenarios",
                  ],
                ].map((row) => (
                  <tr
                    key={row[0]}
                    className="border-b border-gray-200 align-top"
                  >
                    {row.map((cell, i) => (
                      <td
                        key={i}
                        className={`px-4 py-3 ${i === 0 ? "font-semibold text-[#205c38]" : ""}`}
                      >
                        {cell}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section className="mb-14">
          <SectionHeading
            eyebrow="Part 17"
            title="The Lesson 4 Mental Model"
            icon={<LuRoute />}
          >
            <p>
              Lessons 3A–3B built the upper half. Lesson 4 extends the funnel
              into recipient resolution, permission policy, bulk delivery, and
              content generation.
            </p>
          </SectionHeading>

          <MentalModel title="Custom Email evaluation and delivery">
            <div className="mx-auto flex max-w-2xl flex-col items-center">
              <FlowStep icon={<LuRoute />} title="Record / Schedule" />
              <FlowArrow />
              <FlowStep icon={<LuSettings2 />} title="Send Option" />
              <FlowArrow />
              <FlowStep icon={<LuRefreshCw />} title="Event" />
              <FlowArrow />
              <FlowStep icon={<LuGitBranch />} title="Field Criteria" />
              <FlowArrow />
              <FlowStep icon={<LuGitBranch />} title="Boolean Conditions" />
              <FlowArrow />
              <FlowStep icon={<LuUsers />} title="Recipient Resolution" />
              <FlowArrow />
              <FlowStep icon={<LuShield />} title="Permission Policy" />
              <FlowArrow />
              <FlowStep icon={<LuTable2 />} title="Bulk Delivery Policy" />
              <FlowArrow />
              <FlowStep icon={<LuBraces />} title="Content Generation" />
              <FlowArrow />
              <FlowStep icon={<LuSend />} title="Email" final />
            </div>
          </MentalModel>
        </section>

        <section className="mb-14">
          <SectionHeading
            eyebrow="Part 18"
            title="What We Actually Established"
            icon={<LuBadgeCheck />}
          />
          <div className="rounded-2xl border-2 border-[#276749] bg-[#f0fff4] p-6 sm:p-8">
            <div className="grid gap-4 md:grid-cols-2">
              {[
                "Custom Email shares substantial event and Boolean logic with Notifications.",
                "Custom Email also exposes a recurring-schedule send model.",
                "User fields such as Assigned To can dynamically determine recipients.",
                "The reassignment experiment resolved the recipient from the resulting/current Assigned To value.",
                "The previous assignee did not receive the email merely because they were the previous User-field value.",
                "Custom Email Source mode uses Quickbase-specific elements rather than automatically resolving typed legacy-style field strings.",
                "<qb-changes> produced a native structured previous/current change presentation.",
                "A user can be a valid User-field value while lacking the access required to receive the email under permission checking.",
                "Roles and specifically selected users did not circumvent recipient permission checking in our tests.",
                "Ignore recipient permissions materially changed delivery for a user without Tasks access.",
                "Recipient selection and permission policy are separate layers of Custom Email design.",
              ].map((item, index) => (
                <div
                  key={item}
                  className="flex gap-4 rounded-lg border border-[#9fc9ad] bg-white p-4"
                >
                  <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#276749] font-bold text-white">
                    {index + 1}
                  </span>
                  <p className="leading-7">{item}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="overflow-hidden rounded-2xl border border-[#17452a] bg-[#205c38] text-white">
          <div className="p-7 sm:p-9">
            <p className="font-bold uppercase tracking-[0.15em] text-white/75">
              Lesson 4 Final Principle
            </p>
            <h2 className="mt-2 text-3xl font-extrabold sm:text-4xl">
              Custom Email Is a Communication System, Not Merely a
              Better-Looking Notification
            </h2>
            <p className="mt-5 max-w-4xl text-lg leading-8 text-white/90">
              It reuses familiar trigger and condition logic, but extends
              automation into richer recipient resolution, explicit permission
              policy, bulk behavior, modern composition, recurring schedules,
              and richer content.
            </p>
            <p className="mt-4 max-w-4xl text-lg leading-8 text-white/90">
              For new automatic-email designs, Custom Email is generally the
              first mechanism worth evaluating. Existing legacy emails should be
              rebuilt only when doing so solves an actual limitation or produces
              a meaningful design benefit.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Link
                href="/lessons/3b"
                className="inline-flex rounded-lg border-2 border-white px-5 py-3 font-bold text-white hover:bg-white hover:text-[#205c38]"
              >
                ← Review Lesson 3B
              </Link>
              <Link
                href="/lessons"
                className="inline-flex rounded-lg bg-white px-5 py-3 font-bold text-[#205c38] hover:bg-[#f0fff4]"
              >
                View All Lessons
              </Link>
            </div>
          </div>
        </section>
      </article>
    </main>
  );
}
